export const FETCH_WEATHERS = "FETCH_WEATHERS";
export const FETCH_WEATHERS_SUCCESS = "FETCH_WEATHERS_SUCCESS";
export const FETCH_WEATHERS_FAILURE = "FETCH_WEATHERS_FAILURE";
export const SELECTED_DATE = "SELECTED_DATE";
export const SAVE_DATA_FOR_CHARTS = "SAVE_DATA_FOR_CHARTS";
